# Generated by Django 3.2.12 on 2023-02-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_allproducts_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='img',
            field=models.ImageField(upload_to='imgs'),
        ),
    ]
